version: '2'
services:
  app:
    container_name: filestash
    image: shunf4/filestash:latest
    restart: always
    environment:
    - APPLICATION_URL=
    - GDRIVE_CLIENT_ID=<gdrive_client>
    - GDRIVE_CLIENT_SECRET=<gdrive_secret>
    - DROPBOX_CLIENT_ID=<dropbox_key>
    ports:
    - "127.0.0.1:8334:8334"
